version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    command: yarn start
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CRON_PRIVATE_KEY: ${CRON_PRIVATE_KEY}
      POIGNART_CONTRACT: ${POIGNART_CONTRACT}
      RPC_URL: ${RPC_URL}

volumes:
  mongodb_data_container:
