FROM node:16 as base
WORKDIR /usr/src/app

COPY yarn.lock .
COPY tsconfig.json .
COPY codegen.yml .
COPY package.json .
COPY src ./src

ENV MONGODB_URI $MONGODB_URI
ENV JWT_SECRET $JWT_SECRET
ENV CRON_PRIVATE_KEY $CRON_PRIVATE_KEY
ENV POIGNART_CONTRACT $POIGNART_CONTRACT
ENV RPC_URL $RPC_URL
ENV CHAIN_ID $CHAIN_ID
ENV MAX_VOUCHERS $MAX_VOUCHERS
ENV RATE_LIMIT_DURATION $RATE_LIMIT_DURATION
ENV WHITELIST_ADMINS $WHITELIST_ADMINS
ENV FRONTEND_URL $FRONTEND_URL
ENV TWITTER_APP_KEY $TWITTER_APP_KEY
ENV TWITTER_APP_SECRET $TWITTER_APP_SECRET
ENV TWITTER_ACCESS_SECRET $TWITTER_ACCESS_SECRET
ENV TWITTER_ACCESS_TOKEN_SECRET $TWITTER_ACCESS_TOKEN_SECRET

RUN yarn install --frozen-lockfile

CMD ["yarn", "start"]
