version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    command: yarn start
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CRON_PRIVATE_KEY: ${CRON_PRIVATE_KEY}
      POIGNART_CONTRACT: ${POIGNART_CONTRACT}
      RPC_URL: ${RPC_URL}
      CHAIN_ID: ${CHAIN_ID}
      MAX_VOUCHERS: ${MAX_VOUCHERS}
      RATE_LIMIT_DURATION: ${RATE_LIMIT_DURATION}
